steps:
#build the container images:
- name: 'gcr.io/cloud-builders/docker'
  dir: 'cloudrun_manoj_poc'
  #args: ['build', '-t', 'us-east1-docker.pkg.dev/$PROJECT_ID/my-docker-images-repo/svchelloworld2:$COMMIT_SHA','.']
  args: ['build', '-t', 'us-east1-docker.pkg.dev/$PROJECT_ID/my-docker-images-repo/svchelloworld2','.']
#push container image to artifact registry
- name: 'gcr.io/cloud-builders/docker'
  #args: ['push', 'us-east1-docker.pkg.dev/$PROJECT_ID/my-docker-images-repo/svchelloworld2:$COMMIT_SHA']
  args: ['push', 'us-east1-docker.pkg.dev/$PROJECT_ID/my-docker-images-repo/svchelloworld2']

#Debuggin and troubleshooting
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      gcloud --version

      pwd

      ls -la

      cd cloudrun_with_terraform/terraformFiles || exit

      ls -la

#saving a secret inisde a container
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - "-c"
    - |
      echo '***************** DEBUG LINE 1 INSIDE SECRET STEP *****************'
      gcloud secrets list --project=manojproject1-396309
      echo '***************** DEBUG LINE 2 INSIDE SECRET STEP *****************'
      gcloud secrets versions access latest --secret="manoj-saJsonKeyFile-secret-2" > /root/.ssh/keyfile.json
      echo '***************** DEBUG LINE 3 INSIDE SECRET STEP *****************'
      gcloud auth activate-service-account --key-file=/root/.ssh/keyfile.json
      echo '***************** DEBUG LINE 4 INSIDE SECRET STEP *****************'
      gcloud config set project $PROJECT_ID      
      echo '***************** DEBUG LINE 5 INSIDE SECRET STEP ***************** '
  volumes:
    - name: "ssh"
      path: /root/.ssh 

#initialize and apply terraform
- name: 'hashicorp/terraform'
  entrypoint: 'sh'
  args:
    - "-c"
    - |
      echo '***************** DEBUG LINE 1 INSIDE INITIALIZAE TERRAFORM *****************'
      gcloud config set project $PROJECT_ID      

      # # fetch the secret key containing the service account key
      # gcloud secret versions access latest --secret="manoj-saJsonKeyFile-secret" > keyfile.json

      # echo '***************** DEBUG LINE 2 INSIDE INITIALIZAE TERRAFORM *****************'

      # #Authenticate with google cloud using the service account key
      # gcloud auth activate-service-account --key-file=keyfile.json
      # gcloud config set project $PROJECT_ID

      #go inside the folder where terraform files are stored
      cd cloudrun_with_terraform/terraformFiles

      echo '***************** DEBUG LINE 3 INSIDE INITIALIZAE TERRAFORM *****************'

      #Initialize terraform
      terraform init

      #Apply terraform configuration
      terraform apply -auto-approve  
  volumes:
    - name: "ssh"
      path: /root/.ssh 
