steps:
#build the container images:
- name: 'gcr.io/cloud-builders/docker'
  dir: 'cloudrun_manoj_poc'
  args: ['build', '-t', 'us-east1-docker.pkg.dev/$PROJECT_ID/my-docker-images-repo/svchelloworld2:$COMMIT_SHA','.']
#push container image to artifact registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-east1-docker.pkg.dev/$PROJECT_ID/my-docker-images-repo/svchelloworld2:$COMMIT_SHA']
  
#initialize and apply terraform
- name: 'ubuntu'
  entrypoint: 'bash'
  args:
    - "-c"
    - |
      # Install necessary tools
      apt-get update
      apt-get install -y curl gnupg lsb-release

      # Install gcloud SDK
      export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)"
      echo "deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
      curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
      apt-get update && apt-get install -y google-cloud-sdk

      # Install Terraform
      curl -fsSL https://apt.releases.hashicorp.com/gpg | gpg --dearmor -o /usr/local/bin/gpg
      curl -fsSL https://apt.releases.hashicorp.com/gpg | gpg --dearmor -o /usr/local/bin/gpgv
      curl -fsSL https://apt.releases.hashicorp.com/gpg | gpg --dearmor -o /usr/local/bin/gpg-agent
      chmod +x /usr/local/bin/gpg /usr/local/bin/gpgv /usr/local/bin/gpg-agent
      echo "deb [signed-by=/usr/local/bin/gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/hashicorp.list
      apt-get update && apt-get install -y terraform

      # fetch the secret key containing the service account key
      gcloud secret versions access latest --secert="manoj-saJsonKeyFile-secret" > keyfile.json

      #Authenticate with google cloud using the service account key
      gcloud auth activate-service-account --key-file=keyfile.json
      gcloud config set project $PROJECT_ID

      #go inside the folder where terraform files are stored
      cd cloudrun_with_terraform/terraformFiles

      #Initialize terraform
      terraform init

      #Apply terraform configuration
      terraform apply -auto-approve
