steps:
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'testProject1234'
    args: ['build','-t','tmprepo/tmp_image_name','.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push','tmprepo/tmp_image_name',]